using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class AccountTtl : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "accountTtl";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("days")]
        public int Days { get; set; }

    }

}
