using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Animations : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "animations";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("animations")]
        public Animation[] Animations_ { get; set; }

    }

}
