using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Audio : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "audio";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("performer")]
        public string Performer { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_name")]
        public string FileName { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("mime_type")]
        public string MimeType { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("album_cover_thumbnail")]
        public PhotoSize AlbumCoverThumbnail { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("audio")]
        public File Audio_ { get; set; }

    }

}
