using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class AuthorizationState : Structure
    {

        public class AuthorizationStateWaitEncryptionKey : AuthorizationState
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "authorizationStateWaitEncryptionKey";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_encrypted")]
                public bool IsEncrypted { get; set; }

        }

    }

}
