using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class AuthenticationCodeType : Structure
    {

        public class AuthenticationCodeTypeFlashCall : AuthenticationCodeType
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "authenticationCodeTypeFlashCall";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("pattern")]
                public string Pattern { get; set; }

        }

    }

}
