using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class BasicGroupFullInfo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "basicGroupFullInfo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("creator_user_id")]
        public int CreatorUserId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("members")]
        public ChatMember[] Members { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("invite_link")]
        public string InviteLink { get; set; }

    }

}
