using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class BotInfo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "botInfo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("commands")]
        public BotCommand[] Commands { get; set; }

    }

}
