using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class CallbackQueryPayload : Structure
    {

        public class CallbackQueryPayloadData : CallbackQueryPayload
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "callbackQueryPayloadData";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("data")]
                public byte[] Data { get; set; }

        }

    }

}
