using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class CallProtocol : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "callProtocol";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("udp_p2p")]
        public bool UdpP2p { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("udp_reflector")]
        public bool UdpReflector { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("min_layer")]
        public int MinLayer { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("max_layer")]
        public int MaxLayer { get; set; }

    }

}
