using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class CallState : Structure
    {

        public class CallStateError : CallState
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "callStateError";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("error")]
                public Error Error { get; set; }

        }

    }

}
