using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class CallState : Structure
    {

        public class CallStateReady : CallState
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "callStateReady";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("protocol")]
                public CallProtocol Protocol { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("connections")]
                public CallConnection[] Connections { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("config")]
                public string Config { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("encryption_key")]
                public byte[] EncryptionKey { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("emojis")]
                public string[] Emojis { get; set; }

        }

    }

}
