using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class CallState : Structure
    {

        public class CallStateDiscarded : CallState
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "callStateDiscarded";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("reason")]
                public CallDiscardReason Reason { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("need_rating")]
                public bool NeedRating { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("need_debug_information")]
                public bool NeedDebugInformation { get; set; }

        }

    }

}
