using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class CallState : Structure
    {

        public class CallStatePending : CallState
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "callStatePending";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_created")]
                public bool IsCreated { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_received")]
                public bool IsReceived { get; set; }

        }

    }

}
