using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ChatEvents : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "chatEvents";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("events")]
        public ChatEvent[] Events { get; set; }

    }

}
