using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class ChatReportReason : Structure
    {

        public class ChatReportReasonCustom : ChatReportReason
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatReportReasonCustom";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("text")]
                public string Text { get; set; }

        }

    }

}
