using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ChatEventLogFilters : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "chatEventLogFilters";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("message_edits")]
        public bool MessageEdits { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("message_deletions")]
        public bool MessageDeletions { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("message_pins")]
        public bool MessagePins { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("member_joins")]
        public bool MemberJoins { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("member_leaves")]
        public bool MemberLeaves { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("member_invites")]
        public bool MemberInvites { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("member_promotions")]
        public bool MemberPromotions { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("member_restrictions")]
        public bool MemberRestrictions { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("info_changes")]
        public bool InfoChanges { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("setting_changes")]
        public bool SettingChanges { get; set; }

    }

}
