using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ChatInviteLinkInfo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "chatInviteLinkInfo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("chat_id")]
        public long ChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("type")]
        public ChatType Type { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("photo")]
        public ChatPhoto Photo { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("member_count")]
        public int MemberCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("member_user_ids")]
        public int[] MemberUserIds { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_public")]
        public bool IsPublic { get; set; }

    }

}
