using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class ChatEventAction : Structure
    {

        public class ChatEventMessageEdited : ChatEventAction
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatEventMessageEdited";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("old_message")]
                public Message OldMessage { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("new_message")]
                public Message NewMessage { get; set; }

        }

    }

}
