using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class ChatType : Structure
    {

        public class ChatTypeSupergroup : ChatType
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatTypeSupergroup";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("supergroup_id")]
                public int SupergroupId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_channel")]
                public bool IsChannel { get; set; }

        }

    }

}
