using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Chat : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "chat";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("type")]
        public ChatType Type { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("photo")]
        public ChatPhoto Photo { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("last_message")]
        public Message LastMessage { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("order")]
        public Int64 Order { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_pinned")]
        public bool IsPinned { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("can_be_reported")]
        public bool CanBeReported { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("unread_count")]
        public int UnreadCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("last_read_inbox_message_id")]
        public long LastReadInboxMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("last_read_outbox_message_id")]
        public long LastReadOutboxMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("unread_mention_count")]
        public int UnreadMentionCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("notification_settings")]
        public NotificationSettings NotificationSettings { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("reply_markup_message_id")]
        public long ReplyMarkupMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("draft_message")]
        public DraftMessage DraftMessage { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("client_data")]
        public string ClientData { get; set; }

    }

}
