using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ChatPhoto : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "chatPhoto";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("small")]
        public File Small { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("big")]
        public File Big { get; set; }

    }

}
