using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ChatMember : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "chatMember";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("user_id")]
        public int UserId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("inviter_user_id")]
        public int InviterUserId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("joined_chat_date")]
        public int JoinedChatDate { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("status")]
        public ChatMemberStatus Status { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("bot_info")]
        public BotInfo BotInfo { get; set; }

    }

}
