using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class ChatType : Structure
    {

        public class ChatTypePrivate : ChatType
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatTypePrivate";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_id")]
                public int UserId { get; set; }

        }

    }

}
