using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class ChatAction : Structure
    {

        public class ChatActionUploadingDocument : ChatAction
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatActionUploadingDocument";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("progress")]
                public int Progress { get; set; }

        }

    }

}
