using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class ChatEventAction : Structure
    {

        public class ChatEventPhotoChanged : ChatEventAction
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatEventPhotoChanged";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("old_photo")]
                public ChatPhoto OldPhoto { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("new_photo")]
                public ChatPhoto NewPhoto { get; set; }

        }

    }

}
