using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class CheckChatUsernameResult : Structure
    {

        public class CheckChatUsernameResultPublicChatsTooMuch : CheckChatUsernameResult
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "checkChatUsernameResultPublicChatsTooMuch";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

        }

    }

}
