using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ConnectedWebsites : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "connectedWebsites";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("websites")]
        public ConnectedWebsite[] Websites { get; set; }

    }

}
