using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Count : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "count";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("count")]
        public int Count_ { get; set; }

    }

}
