using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class DeviceToken : Structure
    {

        public class DeviceTokenWebPush : DeviceToken
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "deviceTokenWebPush";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("endpoint")]
                public string Endpoint { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("p256dh_base64url")]
                public string P256dhBase64url { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("auth_base64url")]
                public string AuthBase64url { get; set; }

        }

    }

}
