using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Document : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "document";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_name")]
        public string FileName { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("mime_type")]
        public string MimeType { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("thumbnail")]
        public PhotoSize Thumbnail { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("document")]
        public File Document_ { get; set; }

    }

}
