using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class DraftMessage : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "draftMessage";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("reply_to_message_id")]
        public long ReplyToMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("input_message_text")]
        public InputMessageContent InputMessageText { get; set; }

    }

}
