using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Error : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "error";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("code")]
        public int Code { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("message")]
        public string Message { get; set; }

    }

}
