using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class File : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "file";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("size")]
        public int Size { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("expected_size")]
        public int ExpectedSize { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("local")]
        public LocalFile Local { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("remote")]
        public RemoteFile Remote { get; set; }

    }

}
