using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GameHighScores : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "gameHighScores";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("scores")]
        public GameHighScore[] Scores { get; set; }

    }

}
