using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Game : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "game";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("id")]
        public Int64 Id { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("short_name")]
        public string ShortName { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("text")]
        public FormattedText Text { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("photo")]
        public Photo Photo { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("animation")]
        public Animation Animation { get; set; }

    }

}
