using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Hashtags : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "hashtags";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("hashtags")]
        public string[] Hashtags_ { get; set; }

    }

}
