using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ImportedContacts : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "importedContacts";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("user_ids")]
        public int[] UserIds { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("importer_count")]
        public int[] ImporterCount { get; set; }

    }

}
