using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InlineKeyboardButtonType : Structure
    {

        public class InlineKeyboardButtonTypeSwitchInline : InlineKeyboardButtonType
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inlineKeyboardButtonTypeSwitchInline";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("query")]
                public string Query { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("in_current_chat")]
                public bool InCurrentChat { get; set; }

        }

    }

}
