using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InlineKeyboardButtonType : Structure
    {

        public class InlineKeyboardButtonTypeUrl : InlineKeyboardButtonType
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inlineKeyboardButtonTypeUrl";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("url")]
                public string Url { get; set; }

        }

    }

}
