using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InlineQueryResult : Structure
    {

        public class InlineQueryResultVideo : InlineQueryResult
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inlineQueryResultVideo";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("id")]
                public string Id { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("video")]
                public Video Video { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("title")]
                public string Title { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("description")]
                public string Description { get; set; }

        }

    }

}
