using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InlineKeyboardButtonType : Structure
    {

        public class InlineKeyboardButtonTypeCallback : InlineKeyboardButtonType
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inlineKeyboardButtonTypeCallback";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("data")]
                public byte[] Data { get; set; }

        }

    }

}
