using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InputMessageContent : Structure
    {

        public class InputMessageInvoice : InputMessageContent
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inputMessageInvoice";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("invoice")]
                public Invoice Invoice { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("title")]
                public string Title { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("description")]
                public string Description { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("photo_url")]
                public string PhotoUrl { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("photo_size")]
                public int PhotoSize { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("photo_width")]
                public int PhotoWidth { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("photo_height")]
                public int PhotoHeight { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("payload")]
                public byte[] Payload { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("provider_token")]
                public string ProviderToken { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("provider_data")]
                public string ProviderData { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("start_parameter")]
                public string StartParameter { get; set; }

        }

    }

}
