using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class InputThumbnail : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "inputThumbnail";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("thumbnail")]
        public InputFile Thumbnail { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("width")]
        public int Width { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("height")]
        public int Height { get; set; }

    }

}
