using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InputInlineQueryResult : Structure
    {

        public class InputInlineQueryResultArticle : InputInlineQueryResult
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inputInlineQueryResultArticle";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("id")]
                public string Id { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("url")]
                public string Url { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("hide_url")]
                public bool HideUrl { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("title")]
                public string Title { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("description")]
                public string Description { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("thumbnail_url")]
                public string ThumbnailUrl { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("thumbnail_width")]
                public int ThumbnailWidth { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("thumbnail_height")]
                public int ThumbnailHeight { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("reply_markup")]
                public ReplyMarkup ReplyMarkup { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("input_message_content")]
                public InputMessageContent InputMessageContent { get; set; }

        }

    }

}
