using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InputFile : Structure
    {

        public class InputFileRemote : InputFile
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inputFileRemote";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("id")]
                public string Id { get; set; }

        }

    }

}
