using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InputMessageContent : Structure
    {

        public class InputMessageGame : InputMessageContent
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inputMessageGame";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("bot_user_id")]
                public int BotUserId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("game_short_name")]
                public string GameShortName { get; set; }

        }

    }

}
