using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class InputSticker : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "inputSticker";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("png_sticker")]
        public InputFile PngSticker { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("emojis")]
        public string Emojis { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("mask_position")]
        public MaskPosition MaskPosition { get; set; }

    }

}
