using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InputInlineQueryResult : Structure
    {

        public class InputInlineQueryResultAnimatedMpeg4 : InputInlineQueryResult
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inputInlineQueryResultAnimatedMpeg4";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("id")]
                public string Id { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("title")]
                public string Title { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("thumbnail_url")]
                public string ThumbnailUrl { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("mpeg4_url")]
                public string Mpeg4Url { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("mpeg4_duration")]
                public int Mpeg4Duration { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("mpeg4_width")]
                public int Mpeg4Width { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("mpeg4_height")]
                public int Mpeg4Height { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("reply_markup")]
                public ReplyMarkup ReplyMarkup { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("input_message_content")]
                public InputMessageContent InputMessageContent { get; set; }

        }

    }

}
