using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class InputCredentials : Structure
    {

        public class InputCredentialsSaved : InputCredentials
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inputCredentialsSaved";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("saved_credentials_id")]
                public string SavedCredentialsId { get; set; }

        }

    }

}
