using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class LabeledPricePart : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "labeledPricePart";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("amount")]
        public long Amount { get; set; }

    }

}
