using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Location : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "location";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("latitude")]
        public double? Latitude { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("longitude")]
        public double? Longitude { get; set; }

    }

}
