using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class MaskPosition : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "maskPosition";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("point")]
        public MaskPoint Point { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("x_shift")]
        public double? XShift { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("y_shift")]
        public double? YShift { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("scale")]
        public double? Scale { get; set; }

    }

}
