using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageContent : Structure
    {

        public class MessageGameScore : MessageContent
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageGameScore";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("game_message_id")]
                public long GameMessageId { get; set; }

                [JsonConverter(typeof(Converter.Int64))]
                [JsonProperty("game_id")]
                public Int64 GameId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("score")]
                public int Score { get; set; }

        }

    }

}
