using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageForwardInfo : Structure
    {

        public class MessageForwardedFromUser : MessageForwardInfo
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageForwardedFromUser";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("sender_user_id")]
                public int SenderUserId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("date")]
                public int Date { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("forwarded_from_chat_id")]
                public long ForwardedFromChatId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("forwarded_from_message_id")]
                public long ForwardedFromMessageId { get; set; }

        }

    }

}
