using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageContent : Structure
    {

        public class MessageVoiceNote : MessageContent
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageVoiceNote";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("voice_note")]
                public VoiceNote VoiceNote { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("caption")]
                public FormattedText Caption { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_listened")]
                public bool IsListened { get; set; }

        }

    }

}
