using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageContent : Structure
    {

        public class MessageWebsiteConnected : MessageContent
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageWebsiteConnected";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("domain_name")]
                public string DomainName { get; set; }

        }

    }

}
