using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageContent : Structure
    {

        public class MessagePaymentSuccessfulBot : MessageContent
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messagePaymentSuccessfulBot";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("invoice_message_id")]
                public long InvoiceMessageId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("currency")]
                public string Currency { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("total_amount")]
                public long TotalAmount { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("invoice_payload")]
                public byte[] InvoicePayload { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("shipping_option_id")]
                public string ShippingOptionId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("order_info")]
                public OrderInfo OrderInfo { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("telegram_payment_charge_id")]
                public string TelegramPaymentChargeId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("provider_payment_charge_id")]
                public string ProviderPaymentChargeId { get; set; }

        }

    }

}
