using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageContent : Structure
    {

        public class MessageText : MessageContent
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageText";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("text")]
                public FormattedText Text { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("web_page")]
                public WebPage WebPage { get; set; }

        }

    }

}
