using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageContent : Structure
    {

        public class MessageContact : MessageContent
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageContact";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("contact")]
                public Contact Contact { get; set; }

        }

    }

}
