using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class NetworkStatisticsEntry : Structure
    {

        public class NetworkStatisticsEntryFile : NetworkStatisticsEntry
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "networkStatisticsEntryFile";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("file_type")]
                public FileType FileType { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("network_type")]
                public NetworkType NetworkType { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("sent_bytes")]
                public long SentBytes { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("received_bytes")]
                public long ReceivedBytes { get; set; }

        }

    }

}
