using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class NotificationSettingsScope : Structure
    {

        public class NotificationSettingsScopeChat : NotificationSettingsScope
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "notificationSettingsScopeChat";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

        }

    }

}
