using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class NotificationSettings : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "notificationSettings";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("mute_for")]
        public int MuteFor { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("sound")]
        public string Sound { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("show_preview")]
        public bool ShowPreview { get; set; }

    }

}
