using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class OptionValue : Structure
    {

        public class OptionValueBoolean : OptionValue
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "optionValueBoolean";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("value")]
                public bool Value { get; set; }

        }

    }

}
