using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class OptionValue : Structure
    {

        public class OptionValueInteger : OptionValue
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "optionValueInteger";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("value")]
                public int Value { get; set; }

        }

    }

}
