using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PageBlock : Structure
    {

        public class PageBlockChatLink : PageBlock
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "pageBlockChatLink";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("title")]
                public string Title { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("photo")]
                public ChatPhoto Photo { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("username")]
                public string Username { get; set; }

        }

    }

}
