using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PageBlock : Structure
    {

        public class PageBlockVideo : PageBlock
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "pageBlockVideo";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("video")]
                public Video Video { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("caption")]
                public RichText Caption { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("need_autoplay")]
                public bool NeedAutoplay { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_looped")]
                public bool IsLooped { get; set; }

        }

    }

}
