using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PageBlock : Structure
    {

        public class PageBlockCover : PageBlock
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "pageBlockCover";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("cover")]
                public PageBlock Cover { get; set; }

        }

    }

}
