using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PageBlock : Structure
    {

        public class PageBlockAnimation : PageBlock
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "pageBlockAnimation";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("animation")]
                public Animation Animation { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("caption")]
                public RichText Caption { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("need_autoplay")]
                public bool NeedAutoplay { get; set; }

        }

    }

}
