using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PageBlock : Structure
    {

        public class PageBlockAuthorDate : PageBlock
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "pageBlockAuthorDate";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("author")]
                public RichText Author { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("publish_date")]
                public int PublishDate { get; set; }

        }

    }

}
