using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PageBlock : Structure
    {

        public class PageBlockList : PageBlock
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "pageBlockList";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("items")]
                public RichText[] Items { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_ordered")]
                public bool IsOrdered { get; set; }

        }

    }

}
