using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PageBlock : Structure
    {

        public class PageBlockEmbedded : PageBlock
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "pageBlockEmbedded";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("url")]
                public string Url { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("html")]
                public string Html { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("poster_photo")]
                public Photo PosterPhoto { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("width")]
                public int Width { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("height")]
                public int Height { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("caption")]
                public RichText Caption { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_full_width")]
                public bool IsFullWidth { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("allow_scrolling")]
                public bool AllowScrolling { get; set; }

        }

    }

}
