using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class PasswordState : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "passwordState";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("has_password")]
        public bool HasPassword { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("password_hint")]
        public string PasswordHint { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("has_recovery_email_address")]
        public bool HasRecoveryEmailAddress { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("unconfirmed_recovery_email_address_pattern")]
        public string UnconfirmedRecoveryEmailAddressPattern { get; set; }

    }

}
