using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class PasswordRecoveryInfo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "passwordRecoveryInfo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("recovery_email_address_pattern")]
        public string RecoveryEmailAddressPattern { get; set; }

    }

}
