using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class PaymentForm : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "paymentForm";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("invoice")]
        public Invoice Invoice { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("payments_provider")]
        public PaymentsProviderStripe PaymentsProvider { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("saved_order_info")]
        public OrderInfo SavedOrderInfo { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("saved_credentials")]
        public SavedCredentials SavedCredentials { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("can_save_credentials")]
        public bool CanSaveCredentials { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("need_password")]
        public bool NeedPassword { get; set; }

    }

}
