using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class PaymentReceipt : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "paymentReceipt";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("date")]
        public int Date { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("payments_provider_user_id")]
        public int PaymentsProviderUserId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("invoice")]
        public Invoice Invoice { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("order_info")]
        public OrderInfo OrderInfo { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("shipping_option")]
        public ShippingOption ShippingOption { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("credentials_title")]
        public string CredentialsTitle { get; set; }

    }

}
