using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class PaymentsProviderStripe : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "paymentsProviderStripe";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("publishable_key")]
        public string PublishableKey { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("need_country")]
        public bool NeedCountry { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("need_postal_code")]
        public bool NeedPostalCode { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("need_cardholder_name")]
        public bool NeedCardholderName { get; set; }

    }

}
