using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Photo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "photo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("id")]
        public Int64 Id { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("has_stickers")]
        public bool HasStickers { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("sizes")]
        public PhotoSize[] Sizes { get; set; }

    }

}
