using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Proxy : Structure
    {

        public class ProxySocks5 : Proxy
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "proxySocks5";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("server")]
                public string Server { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("port")]
                public int Port { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("username")]
                public string Username { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("password")]
                public string Password { get; set; }

        }

    }

}
