using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class PublicMessageLink : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "publicMessageLink";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("link")]
        public string Link { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("html")]
        public string Html { get; set; }

    }

}
