using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class RecoveryEmailAddress : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "recoveryEmailAddress";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("recovery_email_address")]
        public string RecoveryEmailAddress_ { get; set; }

    }

}
