using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class SecretChatState : Structure
    {

        public class SecretChatStatePending : SecretChatState
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "secretChatStatePending";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

        }

    }

}
