using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Session : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "session";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("id")]
        public Int64 Id { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_current")]
        public bool IsCurrent { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("api_id")]
        public int ApiId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("application_name")]
        public string ApplicationName { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("application_version")]
        public string ApplicationVersion { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_official_application")]
        public bool IsOfficialApplication { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("device_model")]
        public string DeviceModel { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("platform")]
        public string Platform { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("system_version")]
        public string SystemVersion { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("log_in_date")]
        public int LogInDate { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("last_active_date")]
        public int LastActiveDate { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("ip")]
        public string Ip { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("region")]
        public string Region { get; set; }

    }

}
