using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ShippingAddress : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "shippingAddress";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("country_code")]
        public string CountryCode { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("state")]
        public string State { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("city")]
        public string City { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("street_line1")]
        public string StreetLine1 { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("street_line2")]
        public string StreetLine2 { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("postal_code")]
        public string PostalCode { get; set; }

    }

}
