using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ShippingOption : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "shippingOption";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("price_parts")]
        public LabeledPricePart[] PriceParts { get; set; }

    }

}
