using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class StickerSetInfo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "stickerSetInfo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("id")]
        public Int64 Id { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_installed")]
        public bool IsInstalled { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_archived")]
        public bool IsArchived { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_official")]
        public bool IsOfficial { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_masks")]
        public bool IsMasks { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_viewed")]
        public bool IsViewed { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("size")]
        public int Size { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("covers")]
        public Sticker[] Covers { get; set; }

    }

}
