using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Sticker : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "sticker";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("set_id")]
        public Int64 SetId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("width")]
        public int Width { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("emoji")]
        public string Emoji { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_mask")]
        public bool IsMask { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("mask_position")]
        public MaskPosition MaskPosition { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("thumbnail")]
        public PhotoSize Thumbnail { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("sticker")]
        public File Sticker_ { get; set; }

    }

}
