using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Stickers : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "stickers";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("stickers")]
        public Sticker[] Stickers_ { get; set; }

    }

}
