using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class StorageStatisticsByFileType : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "storageStatisticsByFileType";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_type")]
        public FileType FileType { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("size")]
        public long Size { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("count")]
        public int Count { get; set; }

    }

}
