using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class StorageStatistics : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "storageStatistics";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("size")]
        public long Size { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("by_chat")]
        public StorageStatisticsByChat[] ByChat { get; set; }

    }

}
