using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class StorageStatisticsFast : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "storageStatisticsFast";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("files_size")]
        public long FilesSize { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_count")]
        public int FileCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("database_size")]
        public long DatabaseSize { get; set; }

    }

}
