using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class SupergroupMembersFilter : Structure
    {

        public class SupergroupMembersFilterRestricted : SupergroupMembersFilter
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "supergroupMembersFilterRestricted";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("query")]
                public string Query { get; set; }

        }

    }

}
