using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SupergroupFullInfo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "supergroupFullInfo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("member_count")]
        public int MemberCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("administrator_count")]
        public int AdministratorCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("restricted_count")]
        public int RestrictedCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("banned_count")]
        public int BannedCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("can_get_members")]
        public bool CanGetMembers { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("can_set_username")]
        public bool CanSetUsername { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("can_set_sticker_set")]
        public bool CanSetStickerSet { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_all_history_available")]
        public bool IsAllHistoryAvailable { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("sticker_set_id")]
        public Int64 StickerSetId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("invite_link")]
        public string InviteLink { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("pinned_message_id")]
        public long PinnedMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("upgraded_from_basic_group_id")]
        public int UpgradedFromBasicGroupId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("upgraded_from_max_message_id")]
        public long UpgradedFromMaxMessageId { get; set; }

    }

}
