using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TestVectorString : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "testVectorString";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("value")]
        public string[] Value { get; set; }

    }

}
