using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TestBytes : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "testBytes";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("value")]
        public byte[] Value { get; set; }

    }

}
