using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TextEntities : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "textEntities";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("entities")]
        public TextEntity[] Entities { get; set; }

    }

}
