using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TextEntity : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "textEntity";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("offset")]
        public int Offset { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("length")]
        public int Length { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("type")]
        public TextEntityType Type { get; set; }

    }

}
