using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TMeUrl : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "tMeUrl";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("type")]
        public TMeUrlType Type { get; set; }

    }

}
