using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TMeUrls : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "tMeUrls";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("urls")]
        public TMeUrl[] Urls { get; set; }

    }

}
