using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TMeUrlType : Structure
    {

        public class TMeUrlTypeSupergroup : TMeUrlType
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "tMeUrlTypeSupergroup";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("supergroup_id")]
                public long SupergroupId { get; set; }

        }

    }

}
