using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateBasicGroupFullInfo : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateBasicGroupFullInfo";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("basic_group_id")]
                public int BasicGroupId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("basic_group_full_info")]
                public BasicGroupFullInfo BasicGroupFullInfo { get; set; }

        }

    }

}
