using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateOption : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateOption";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("name")]
                public string Name { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("value")]
                public OptionValue Value { get; set; }

        }

    }

}
