using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateMessageSendFailed : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateMessageSendFailed";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("message")]
                public Message Message { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("old_message_id")]
                public long OldMessageId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("error_code")]
                public int ErrorCode { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("error_message")]
                public string ErrorMessage { get; set; }

        }

    }

}
