using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateAuthorizationState : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateAuthorizationState";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("authorization_state")]
                public AuthorizationState AuthorizationState { get; set; }

        }

    }

}
