using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateCall : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateCall";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("call")]
                public Call Call { get; set; }

        }

    }

}
