using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateUnreadMessageCount : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateUnreadMessageCount";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("unread_count")]
                public int UnreadCount { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("unread_unmuted_count")]
                public int UnreadUnmutedCount { get; set; }

        }

    }

}
