using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateBasicGroup : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateBasicGroup";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("basic_group")]
                public BasicGroup BasicGroup { get; set; }

        }

    }

}
