using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateChatUnreadMentionCount : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateChatUnreadMentionCount";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("unread_mention_count")]
                public int UnreadMentionCount { get; set; }

        }

    }

}
