using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateConnectionState : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateConnectionState";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("state")]
                public ConnectionState State { get; set; }

        }

    }

}
