using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateFile : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateFile";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("file")]
                public File File { get; set; }

        }

    }

}
