using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateServiceNotification : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateServiceNotification";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("type")]
                public string Type { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("content")]
                public MessageContent Content { get; set; }

        }

    }

}
