using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateNewShippingQuery : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateNewShippingQuery";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter.Int64))]
                [JsonProperty("id")]
                public Int64 Id { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("sender_user_id")]
                public int SenderUserId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("invoice_payload")]
                public string InvoicePayload { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("shipping_address")]
                public ShippingAddress ShippingAddress { get; set; }

        }

    }

}
