using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateTrendingStickerSets : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateTrendingStickerSets";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("sticker_sets")]
                public StickerSets StickerSets { get; set; }

        }

    }

}
