using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateChatIsPinned : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateChatIsPinned";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_pinned")]
                public bool IsPinned { get; set; }

                [JsonConverter(typeof(Converter.Int64))]
                [JsonProperty("order")]
                public Int64 Order { get; set; }

        }

    }

}
