using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateDeleteMessages : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateDeleteMessages";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("message_ids")]
                public long[] MessageIds { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_permanent")]
                public bool IsPermanent { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("from_cache")]
                public bool FromCache { get; set; }

        }

    }

}
