using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateFileGenerationStop : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateFileGenerationStop";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter.Int64))]
                [JsonProperty("generation_id")]
                public Int64 GenerationId { get; set; }

        }

    }

}
