using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateUserChatAction : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateUserChatAction";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_id")]
                public int UserId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("action")]
                public ChatAction Action { get; set; }

        }

    }

}
