using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateUser : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateUser";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("user")]
                public User User { get; set; }

        }

    }

}
