using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateUserStatus : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateUserStatus";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_id")]
                public int UserId { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("status")]
                public UserStatus Status { get; set; }

        }

    }

}
