using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public class UpdateUserPrivacySettingRules : Update
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateUserPrivacySettingRules";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("setting")]
                public UserPrivacySetting Setting { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("rules")]
                public UserPrivacySettingRules Rules { get; set; }

        }

    }

}
