using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class UserPrivacySettingRules : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "userPrivacySettingRules";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("rules")]
        public UserPrivacySettingRule[] Rules { get; set; }

    }

}
