using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class UserFullInfo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "userFullInfo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_blocked")]
        public bool IsBlocked { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("can_be_called")]
        public bool CanBeCalled { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("has_private_calls")]
        public bool HasPrivateCalls { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("bio")]
        public string Bio { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("share_text")]
        public string ShareText { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("group_in_common_count")]
        public int GroupInCommonCount { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("bot_info")]
        public BotInfo BotInfo { get; set; }

    }

}
