using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class UserType : Structure
    {

        public class UserTypeRegular : UserType
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "userTypeRegular";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

        }

    }

}
