using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class UserPrivacySettingRule : Structure
    {

        public class UserPrivacySettingRuleAllowUsers : UserPrivacySettingRule
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "userPrivacySettingRuleAllowUsers";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_ids")]
                public int[] UserIds { get; set; }

        }

    }

}
