using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class UserStatus : Structure
    {

        public class UserStatusOnline : UserStatus
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "userStatusOnline";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("expires")]
                public int Expires { get; set; }

        }

    }

}
