using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class UserStatus : Structure
    {

        public class UserStatusOffline : UserStatus
        {

                [JsonProperty("@type")]
                public override string DataType { get; set; } = "userStatusOffline";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("was_online")]
                public int WasOnline { get; set; }

        }

    }

}
