using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ValidatedOrderInfo : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "validatedOrderInfo";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("order_info_id")]
        public string OrderInfoId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("shipping_options")]
        public ShippingOption[] ShippingOptions { get; set; }

    }

}
