using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Venue : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "venue";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("provider")]
        public string Provider { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("id")]
        public string Id { get; set; }

    }

}
