using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class VideoNote : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "videoNote";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("length")]
        public int Length { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("thumbnail")]
        public PhotoSize Thumbnail { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("video")]
        public File Video { get; set; }

    }

}
