using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class VoiceNote : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "voiceNote";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("waveform")]
        public byte[] Waveform { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("mime_type")]
        public string MimeType { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("voice")]
        public File Voice { get; set; }

    }

}
