using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class Wallpapers : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "wallpapers";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("wallpapers")]
        public Wallpaper[] Wallpapers_ { get; set; }

    }

}
