using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class WebPageInstantView : Structure
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "webPageInstantView";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("page_blocks")]
        public PageBlock[] PageBlocks { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_full")]
        public bool IsFull { get; set; }

    }

}
