using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class AcceptCall : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "acceptCall";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("call_id")]
        public int CallId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("protocol")]
        public CallProtocol Protocol { get; set; }

    }

}
