using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class AddNetworkStatistics : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "addNetworkStatistics";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("entry")]
        public NetworkStatisticsEntry Entry { get; set; }

    }

}
