using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class AddStickerToSet : Method<StickerSet>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "addStickerToSet";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("user_id")]
        public int UserId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("sticker")]
        public InputSticker Sticker { get; set; }

    }

}
