using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class AnswerShippingQuery : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "answerShippingQuery";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("shipping_query_id")]
        public Int64 ShippingQueryId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("shipping_options")]
        public ShippingOption[] ShippingOptions { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("error_message")]
        public string ErrorMessage { get; set; }

    }

}
