using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class AnswerInlineQuery : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "answerInlineQuery";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("inline_query_id")]
        public Int64 InlineQueryId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_personal")]
        public bool IsPersonal { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("results")]
        public InputInlineQueryResult[] Results { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("cache_time")]
        public int CacheTime { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("next_offset")]
        public string NextOffset { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("switch_pm_text")]
        public string SwitchPmText { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("switch_pm_parameter")]
        public string SwitchPmParameter { get; set; }

    }

}
