using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class CancelDownloadFile : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "cancelDownloadFile";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_id")]
        public int FileId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("only_if_pending")]
        public bool OnlyIfPending { get; set; }

    }

}
