using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ChangeImportedContacts : Method<ImportedContacts>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "changeImportedContacts";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("contacts")]
        public Contact[] Contacts { get; set; }

    }

}
