using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ChangeChatReportSpamState : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "changeChatReportSpamState";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("chat_id")]
        public long ChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_spam_chat")]
        public bool IsSpamChat { get; set; }

    }

}
