using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class CheckAuthenticationBotToken : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "checkAuthenticationBotToken";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("token")]
        public string Token { get; set; }

    }

}
