using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class CheckChatUsername : Method<CheckChatUsernameResult>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "checkChatUsername";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("chat_id")]
        public Int64 ChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("username")]
        public string Username { get; set; }

    }

}
