using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class CheckChangePhoneNumberCode : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "checkChangePhoneNumberCode";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("code")]
        public string Code { get; set; }

    }

}
