using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class CreateTemporaryPassword : Method<TemporaryPasswordState>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "createTemporaryPassword";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("valid_for")]
        public int ValidFor { get; set; }

    }

}
