using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class CreateNewSupergroupChat : Method<Chat>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "createNewSupergroupChat";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_channel")]
        public bool IsChannel { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("description")]
        public string Description { get; set; }

    }

}
