using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class DiscardCall : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "discardCall";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("call_id")]
        public int CallId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_disconnected")]
        public bool IsDisconnected { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("connection_id")]
        public Int64 ConnectionId { get; set; }

    }

}
