using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class EditInlineMessageText : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "editInlineMessageText";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("inline_message_id")]
        public string InlineMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("reply_markup")]
        public ReplyMarkup ReplyMarkup { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("input_message_content")]
        public InputMessageContent InputMessageContent { get; set; }

    }

}
