using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetArchivedStickerSets : Method<StickerSets>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getArchivedStickerSets";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_masks")]
        public bool IsMasks { get; set; }

        [JsonConverter(typeof(Converter.Int64))]
        [JsonProperty("offset_sticker_set_id")]
        public Int64 OffsetStickerSetId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("limit")]
        public int Limit { get; set; }

    }

}
