using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetBasicGroup : Method<BasicGroup>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getBasicGroup";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("basic_group_id")]
        public int BasicGroupId { get; set; }

    }

}
