using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetChatMessageByDate : Method<Message>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getChatMessageByDate";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("chat_id")]
        public long ChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("date")]
        public int Date { get; set; }

    }

}
