using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetChatHistory : Method<Messages>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getChatHistory";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("chat_id")]
        public long ChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("from_message_id")]
        public long FromMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("offset")]
        public int Offset { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("limit")]
        public int Limit { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("only_local")]
        public bool OnlyLocal { get; set; }

    }

}
