using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetConnectedWebsites : Method<ConnectedWebsites>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getConnectedWebsites";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

    }

}
