using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetFileMimeType : Method<Text>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getFileMimeType";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_name")]
        public string FileName { get; set; }

    }

}
