using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetFile : Method<File>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getFile";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_id")]
        public int FileId { get; set; }

    }

}
