using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetFileExtension : Method<Text>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getFileExtension";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("mime_type")]
        public string MimeType { get; set; }

    }

}
