using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetGroupsInCommon : Method<Chats>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getGroupsInCommon";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("user_id")]
        public int UserId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("offset_chat_id")]
        public long OffsetChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("limit")]
        public int Limit { get; set; }

    }

}
