using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetInstalledStickerSets : Method<StickerSets>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getInstalledStickerSets";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_masks")]
        public bool IsMasks { get; set; }

    }

}
