using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetNotificationSettings : Method<NotificationSettings>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getNotificationSettings";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("scope")]
        public NotificationSettingsScope Scope { get; set; }

    }

}
