using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetNetworkStatistics : Method<NetworkStatistics>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getNetworkStatistics";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("only_current")]
        public bool OnlyCurrent { get; set; }

    }

}
