using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetOption : Method<OptionValue>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getOption";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("name")]
        public string Name { get; set; }

    }

}
