using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetRemoteFile : Method<File>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getRemoteFile";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("remote_file_id")]
        public string RemoteFileId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_type")]
        public FileType FileType { get; set; }

    }

}
