using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetRecoveryEmailAddress : Method<RecoveryEmailAddress>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getRecoveryEmailAddress";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("password")]
        public string Password { get; set; }

    }

}
