using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetRecentlyVisitedTMeUrls : Method<TMeUrls>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getRecentlyVisitedTMeUrls";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("referrer")]
        public string Referrer { get; set; }

    }

}
