using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetSupergroupMembers : Method<ChatMembers>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getSupergroupMembers";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("supergroup_id")]
        public int SupergroupId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("filter")]
        public SupergroupMembersFilter Filter { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("offset")]
        public int Offset { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("limit")]
        public int Limit { get; set; }

    }

}
