using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetTextEntities : Method<TextEntities>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getTextEntities";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("text")]
        public string Text { get; set; }

    }

}
