using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetUserPrivacySettingRules : Method<UserPrivacySettingRules>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getUserPrivacySettingRules";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("setting")]
        public UserPrivacySetting Setting { get; set; }

    }

}
