using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetWebPagePreview : Method<WebPage>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getWebPagePreview";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("text")]
        public FormattedText Text { get; set; }

    }

}
