using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class GetWebPageInstantView : Method<WebPageInstantView>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "getWebPageInstantView";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("force_full")]
        public bool ForceFull { get; set; }

    }

}
