using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class PinSupergroupMessage : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "pinSupergroupMessage";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("supergroup_id")]
        public int SupergroupId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("message_id")]
        public long MessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("disable_notification")]
        public bool DisableNotification { get; set; }

    }

}
