using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class RegisterDevice : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "registerDevice";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("device_token")]
        public DeviceToken DeviceToken { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("other_user_ids")]
        public int[] OtherUserIds { get; set; }

    }

}
