using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class RemoveRecentHashtag : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "removeRecentHashtag";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("hashtag")]
        public string Hashtag { get; set; }

    }

}
