using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ReportSupergroupSpam : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "reportSupergroupSpam";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("supergroup_id")]
        public int SupergroupId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("user_id")]
        public int UserId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("message_ids")]
        public long[] MessageIds { get; set; }

    }

}
