using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SearchMessages : Method<Messages>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "searchMessages";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("query")]
        public string Query { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("offset_date")]
        public int OffsetDate { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("offset_chat_id")]
        public long OffsetChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("offset_message_id")]
        public long OffsetMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("limit")]
        public int Limit { get; set; }

    }

}
