using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SearchChatMessages : Method<Messages>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "searchChatMessages";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("chat_id")]
        public long ChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("query")]
        public string Query { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("sender_user_id")]
        public int SenderUserId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("from_message_id")]
        public long FromMessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("offset")]
        public int Offset { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("limit")]
        public int Limit { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("filter")]
        public SearchMessagesFilter Filter { get; set; }

    }

}
