using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SendCustomRequest : Method<CustomRequestResult>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "sendCustomRequest";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("method")]
        public string Method { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("parameters")]
        public string Parameters { get; set; }

    }

}
