using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SendCallDebugInformation : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "sendCallDebugInformation";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("call_id")]
        public int CallId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("debug_information")]
        public string DebugInformation { get; set; }

    }

}
