using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SendPaymentForm : Method<PaymentResult>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "sendPaymentForm";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("chat_id")]
        public long ChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("message_id")]
        public long MessageId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("order_info_id")]
        public string OrderInfoId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("shipping_option_id")]
        public string ShippingOptionId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("credentials")]
        public InputCredentials Credentials { get; set; }

    }

}
