using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetAccountTtl : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setAccountTtl";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("ttl")]
        public AccountTtl Ttl { get; set; }

    }

}
