using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetAlarm : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setAlarm";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("seconds")]
        public double? Seconds { get; set; }

    }

}
