using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetBio : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setBio";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("bio")]
        public string Bio { get; set; }

    }

}
