using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetChatDraftMessage : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setChatDraftMessage";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("chat_id")]
        public long ChatId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("draft_message")]
        public DraftMessage DraftMessage { get; set; }

    }

}
