using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetDatabaseEncryptionKey : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setDatabaseEncryptionKey";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("new_encryption_key")]
        public byte[] NewEncryptionKey { get; set; }

    }

}
