using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetOption : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setOption";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("value")]
        public OptionValue Value { get; set; }

    }

}
