using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetProxy : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setProxy";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("proxy")]
        public Proxy Proxy { get; set; }

    }

}
