using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetProfilePhoto : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setProfilePhoto";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("photo")]
        public InputFile Photo { get; set; }

    }

}
