using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetPassword : Method<PasswordState>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setPassword";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("old_password")]
        public string OldPassword { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("new_password")]
        public string NewPassword { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("new_hint")]
        public string NewHint { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("set_recovery_email_address")]
        public bool SetRecoveryEmailAddress { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("new_recovery_email_address")]
        public string NewRecoveryEmailAddress { get; set; }

    }

}
