using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetPinnedChats : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setPinnedChats";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("chat_ids")]
        public long[] ChatIds { get; set; }

    }

}
