using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetRecoveryEmailAddress : Method<PasswordState>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setRecoveryEmailAddress";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("new_recovery_email_address")]
        public string NewRecoveryEmailAddress { get; set; }

    }

}
