using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetUserPrivacySettingRules : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setUserPrivacySettingRules";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("setting")]
        public UserPrivacySetting Setting { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("rules")]
        public UserPrivacySettingRules Rules { get; set; }

    }

}
