using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class SetUsername : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "setUsername";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("username")]
        public string Username { get; set; }

    }

}
