using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TestSquareInt : Method<TestInt>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "testSquareInt";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("x")]
        public int X { get; set; }

    }

}
