using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TestCallBytes : Method<TestBytes>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "testCallBytes";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("x")]
        public byte[] X { get; set; }

    }

}
