using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class TestCallVectorIntObject : Method<TestVectorIntObject>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "testCallVectorIntObject";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("x")]
        public TestInt[] X { get; set; }

    }

}
