using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ToggleSupergroupInvites : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "toggleSupergroupInvites";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("supergroup_id")]
        public int SupergroupId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("anyone_can_invite")]
        public bool AnyoneCanInvite { get; set; }

    }

}
