using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ToggleSupergroupSignMessages : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "toggleSupergroupSignMessages";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("supergroup_id")]
        public int SupergroupId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("sign_messages")]
        public bool SignMessages { get; set; }

    }

}
