using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ToggleSupergroupIsAllHistoryAvailable : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "toggleSupergroupIsAllHistoryAvailable";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("supergroup_id")]
        public int SupergroupId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("is_all_history_available")]
        public bool IsAllHistoryAvailable { get; set; }

    }

}
