using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class ToggleBasicGroupAdministrators : Method<Ok>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "toggleBasicGroupAdministrators";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("basic_group_id")]
        public int BasicGroupId { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("everyone_is_administrator")]
        public bool EveryoneIsAdministrator { get; set; }

    }

}
