using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public class UploadFile : Method<File>
    {

        [JsonProperty("@type")]
        public override string DataType { get; set; } = "uploadFile";

        [JsonProperty("@extra")]
        public override string Extra { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file")]
        public InputFile File { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("file_type")]
        public FileType FileType { get; set; }

        [JsonConverter(typeof(Converter))]
        [JsonProperty("priority")]
        public int Priority { get; set; }

    }

}
